title: Università di Siena
description: Manuale per i compilatori
theme: just-the-docs

url: https://github.com/petrarchsitinera/manuale/.github.io

aux_links:
  Template Repository: https://github.com/petrarchsitinera/manuale/
